// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog_id_ from "./routes/blog/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $LikeButton from "./islands/LikeButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/[id].tsx": $blog_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/LikeButton.tsx": $LikeButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
